package com.Infogain.EHS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(targetNamespace="xmlns.services.errorhandler/FaultSchema.xsd",
  name="EHServicePortType")
@XmlSeeAlso(
  { errorhandler.services.xmlns.faultschema.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface EHServicePortType
{
  @WebMethod(operationName="LogFaultMsg", action="xmlns.services.errorhandler/FaultSchema.xsd/LogFaultMsg")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="xmlns.services.errorhandler/FaultSchema.xsd/LogFaultMsg",
    output="xmlns.services.errorhandler/FaultSchema.xsd/EHServicePortType/LogFaultMsgResponse")
  public void logFaultMsg(@WebParam(targetNamespace="xmlns.services.errorhandler/FaultSchema.xsd",
      partName="Payload", name="FaultSchema", mode=Mode.INOUT)
    Holder<errorhandler.services.xmlns.faultschema.FaultSchema> Payload);
}
