<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="ReceiveData.wsdl"/>
      <rootElement name="FaultSchema" namespace="xmlns.netapp.com/FaultSchema.xsd"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="PublishToGenericEHS.wsdl"/>
      <rootElement name="FaultSchema" namespace="xmlns.netapp.com/FaultSchema.xsd"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.5.0(build 090730.0200.1754) AT [SAT OCT 22 13:43:34 PDT 2011]. -->
?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:imp1="xmlns.netapp.com/FaultSchema.xsd" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:ns0="http://www.w3.org/2001/XMLSchema" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/PublishToGenericEHS/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/ReceiveData/" xmlns:hdr="http://xmlns.oracle.com/pcbpel/adapter/jms/" exclude-result-prefixes="xsl plt imp1 pc ns0 jca tns hdr ns1 bpws ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <imp1:FaultSchema>
      <imp1:Header>
        <imp1:MessageID>
          <xsl:value-of select="/imp1:FaultSchema/imp1:Header/imp1:MessageID"/>
        </imp1:MessageID>
        <imp1:MessageName>
          <xsl:value-of select="/imp1:FaultSchema/imp1:Header/imp1:MessageName"/>
        </imp1:MessageName>
        <imp1:BusinessObjectID>
          <xsl:value-of select="/imp1:FaultSchema/imp1:Header/imp1:BusinessObjectID"/>
        </imp1:BusinessObjectID>
        <imp1:CreationDateTime>
          <xsl:value-of select="/imp1:FaultSchema/imp1:Header/imp1:CreationDateTime"/>
        </imp1:CreationDateTime>
        <imp1:RequestID>
          <xsl:value-of select="/imp1:FaultSchema/imp1:Header/imp1:RequestID"/>
        </imp1:RequestID>
        <imp1:VerbCode>
          <xsl:value-of select="/imp1:FaultSchema/imp1:Header/imp1:VerbCode"/>
        </imp1:VerbCode>
        <imp1:Sender>
          <xsl:value-of select="/imp1:FaultSchema/imp1:Header/imp1:Sender"/>
        </imp1:Sender>
        <imp1:Target>
          <xsl:value-of select="/imp1:FaultSchema/imp1:Header/imp1:Target"/>
        </imp1:Target>
      </imp1:Header>
      <imp1:FaultService>
        <imp1:TransactionID>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultService/imp1:TransactionID"/>
        </imp1:TransactionID>
        <imp1:ImplementationCode>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultService/imp1:ImplementationCode"/>
        </imp1:ImplementationCode>
        <imp1:ProcessInstanceID>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultService/imp1:ProcessInstanceID"/>
        </imp1:ProcessInstanceID>
        <imp1:InterfaceName>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultService/imp1:InterfaceName"/>
        </imp1:InterfaceName>
      </imp1:FaultService>
      <imp1:FaultMessage>
        <imp1:ErrorCode>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultMessage/imp1:ErrorCode"/>
        </imp1:ErrorCode>
        <imp1:ErrorMsg>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultMessage/imp1:ErrorMsg"/>
        </imp1:ErrorMsg>
        <imp1:Severity>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultMessage/imp1:Severity"/>
        </imp1:Severity>
        <imp1:StackTrace>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultMessage/imp1:StackTrace"/>
        </imp1:StackTrace>
        <imp1:Payload>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultMessage/imp1:Payload"/>
        </imp1:Payload>
        <imp1:ExtraInfo1>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultMessage/imp1:ExtraInfo1"/>
        </imp1:ExtraInfo1>
        <imp1:ExtraInfo2>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultMessage/imp1:ExtraInfo2"/>
        </imp1:ExtraInfo2>
        <imp1:ExtraInfo3>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultMessage/imp1:ExtraInfo3"/>
        </imp1:ExtraInfo3>
        <imp1:ExtraInfo4>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultMessage/imp1:ExtraInfo4"/>
        </imp1:ExtraInfo4>
      </imp1:FaultMessage>
      <imp1:FaultNotification>
        <imp1:ReportingDateTime>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultNotification/imp1:ReportingDateTime"/>
        </imp1:ReportingDateTime>
        <imp1:CorrectiveAction>
          <xsl:value-of select="/imp1:FaultSchema/imp1:FaultNotification/imp1:CorrectiveAction"/>
        </imp1:CorrectiveAction>
      </imp1:FaultNotification>
    </imp1:FaultSchema>
  </xsl:template>
</xsl:stylesheet>
